spring:
  application:
    name: Tiendadb
  datasource:
    url: jdbc:mysql://azuretienda.mysql.database.azure.com:3306/Tiendadb?useSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true
    username: adminaz
    password: Vedruna2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
